### PR TITLE
Modifications and New Videos Page

### PR DESCRIPTION
**Pull request by nanoproductions**
- [x] New Videos Page
- [x] Updated About Page
- [x] Added alert to Home Page
- [x] Using DOM Manipulation made Navbar dynamic
- [x] Changed folder structure

### CODE REVIEW

**Comment by chaziei** [comment]
oops, should have looked at this before pushing from my pc with some extra changes

**Comment by nanoproductions** [comment]
Fixed all conflicts! Should be ready for merge.

**Comment by chaziei** [comment]
:D

**Comment by chaziei** [comment]
it wont let me merge

**Pull request closed without merging**
